version: "3.7"
services:
  # Start Mosquitto MQTT
  mosquitto:
    image: eclipse-mosquitto   # Ime slike
    container_name: mosquitto_custom  # Ime kontejnerja
    ports:
      - "1883:1883"            # MQTT privzeti port
    volumes:                   # Priklop konfiguracijske datoteke v kontejner
      - ./data_mosquitto:/etc/mosquitto                                   
      - ./data_mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf  # Potrebno ustvariti datoteko mosquitto.conf
      
  # Start Mosquitto MQTT Exporter
  exporter:
    image: sapcc/mosquitto-exporter    # Ime slike
    container_name: mosquitto-exporter # Ime kontejnerja
    ports:
      - "9234:9234"                    # Exporter privzeti port
    environment:                       # Nastavitev naslova za MQTT broker
      - "BROKER_ENDPOINT=tcp://mosquitto:1883"

  # Start Prometheus
  prometheus:
    image: prom/prometheus     # Ime slike
    container_name: prometheus # Ime kontejnerja
    ports:
      - "9090:9090"            # Prometheus privzeti port
    volumes:                   # Priklop konfiguracijske datoteke v kontejner
      - ./data_prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Start Grafana
  grafana:
    image: grafana/grafana     # Ime slike
    container_name: grafana    # Ime kontejnerja
    ports:
     - "3000:3000"             # Grafana privzeti port